version: '2'
services:
  unms:
    image: nico640/docker-unms:latest
    restart: always
    ports:
      - 80:80
      - 9443:443
      - 2055:2055/udp
    environment:
      - TZ=Europe/London
    volumes:
      - /volume1/docker/unms:/config
